// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX31rQXeXgxlPmPtU89cYMYIURZRGJjXI',
    appId: '1:610294755672:web:e31d00a7192957478f352d',
    messagingSenderId: '610294755672',
    projectId: 'youtogether-94a46',
    authDomain: 'youtogether-94a46.firebaseapp.com',
    databaseURL:
        'https://youtogether-94a46-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'youtogether-94a46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwKHhGRZXWw_YPbdMqqbwHj1nIy8l3Bo4',
    appId: '1:610294755672:android:9d2484ae65f37c748f352d',
    messagingSenderId: '610294755672',
    projectId: 'youtogether-94a46',
    databaseURL:
        'https://youtogether-94a46-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'youtogether-94a46.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfbqUZH0sfCncxfcesUZXWzKkh0hcR1TQ',
    appId: '1:610294755672:ios:c2ed5efd1a9a9d848f352d',
    messagingSenderId: '610294755672',
    projectId: 'youtogether-94a46',
    databaseURL:
        'https://youtogether-94a46-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'youtogether-94a46.firebasestorage.app',
    iosBundleId: 'com.youtogether.youtogether',
  );
}
