#!/usr/bin/env bash
# .githooks/scripts/validate_commit_msg.sh
#
# Validates a commit message against the Conventional Commits 1.0.0 specification.
#
# Usage:
#   validate_commit_msg.sh <commit-message-file>
#
# Called by lefthook on the commit-msg hook.
# Can also be run manually for testing:
#   echo "feat(auth): implement login" | bash .githooks/scripts/validate_commit_msg.sh /dev/stdin
#
# Debug mode (prints pattern and raw message):
#   HOOK_DEBUG=1 bash .githooks/scripts/validate_commit_msg.sh .git/COMMIT_EDITMSG

set -euo pipefail

# ---------------------------------------------------------------------------
# ANSI colour codes
# Disabled automatically when the output is not a terminal (e.g. CI logs).
# ---------------------------------------------------------------------------
if [ -t 1 ] && [ "${NO_COLOR:-}" = "" ]; then
  RED='\033[0;31m'
  YELLOW='\033[0;33m'
  GREEN='\033[0;32m'
  CYAN='\033[0;36m'
  BOLD='\033[1m'
  DIM='\033[2m'
  RESET='\033[0m'
else
  RED='' YELLOW='' GREEN='' CYAN='' BOLD='' DIM='' RESET=''
fi

# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------
log_info()    { echo -e "${CYAN}[hook]${RESET} $*"; }
log_success() { echo -e "${GREEN}[hook]${RESET} $*"; }
log_warn()    { echo -e "${YELLOW}[hook]${RESET} $*"; }
log_error()   { echo -e "${RED}${BOLD}[hook] ERROR${RESET} $*" >&2; }
log_debug()   { [ "${HOOK_DEBUG:-0}" = "1" ] && echo -e "${DIM}[hook:debug]${RESET} $*" || true; }

# ---------------------------------------------------------------------------
# Input
# ---------------------------------------------------------------------------
COMMIT_MSG_FILE="${1:-}"

if [ -z "$COMMIT_MSG_FILE" ]; then
  log_error "No commit message file provided."
  log_error "Usage: $0 <commit-message-file>"
  exit 1
fi

if [ ! -f "$COMMIT_MSG_FILE" ]; then
  log_error "File not found: $COMMIT_MSG_FILE"
  exit 1
fi

# Read only the first non-empty line (the subject line).
MSG=$(grep -m1 "^[^#]" "$COMMIT_MSG_FILE" || true)
MSG=$(echo "$MSG" | sed 's/[[:space:]]*$//')

log_debug "Commit message file : $COMMIT_MSG_FILE"
log_debug "Subject line        : $MSG"

# ---------------------------------------------------------------------------
# Exemptions — commits that must not be validated
# ---------------------------------------------------------------------------

# Merge commits generated by Git.
if echo "$MSG" | grep -qE '^Merge '; then
  log_debug "Merge commit detected — skipping validation."
  exit 0
fi

# Revert commits generated by git revert.
if echo "$MSG" | grep -qE '^Revert "'; then
  log_debug "Revert commit detected — skipping validation."
  exit 0
fi

# Release PRs created by release-please.
if echo "$MSG" | grep -qE '^chore\(main\): release '; then
  log_debug "release-please commit detected — skipping validation."
  exit 0
fi

# ---------------------------------------------------------------------------
# Conventional Commits pattern
#
# Format : <type>(<scope>): <description>
#
# type        : one of the allowed keywords (lowercase)
# scope       : optional, lowercase alphanumeric with hyphens, in parentheses
# description : 1–100 characters, must not be empty
# ---------------------------------------------------------------------------
ALLOWED_TYPES="feat|fix|docs|style|refactor|test|chore|ci|build|perf|revert"
PATTERN="^(${ALLOWED_TYPES})(\([a-z][a-z0-9-]*\))?: .{1,100}$"

log_debug "Pattern : $PATTERN"

if echo "$MSG" | grep -qE "$PATTERN"; then
  log_success "Commit message is valid."
  exit 0
fi

# ---------------------------------------------------------------------------
# Failure — produce a detailed, actionable error message
# ---------------------------------------------------------------------------
echo ""
log_error "Commit message does not conform to the Conventional Commits specification."
echo ""
echo -e "  ${BOLD}Expected format:${RESET}"
echo -e "  ${GREEN}<type>${RESET}${DIM}(<scope>)${RESET}: <short description>"
echo ""
echo -e "  ${BOLD}Allowed types:${RESET}"
echo -e "  ${CYAN}feat${RESET}     — new feature (MINOR version bump)"
echo -e "  ${CYAN}fix${RESET}      — bug fix (PATCH version bump)"
echo -e "  ${CYAN}refactor${RESET} — code restructuring, no behaviour change"
echo -e "  ${CYAN}test${RESET}     — adding or correcting tests"
echo -e "  ${CYAN}docs${RESET}     — documentation only"
echo -e "  ${CYAN}chore${RESET}    — build scripts, dependencies, tooling"
echo -e "  ${CYAN}ci${RESET}       — CI/CD pipeline changes"
echo -e "  ${CYAN}style${RESET}    — formatting, no logic change"
echo -e "  ${CYAN}perf${RESET}     — performance improvements"
echo -e "  ${CYAN}build${RESET}    — build system changes"
echo -e "  ${CYAN}revert${RESET}   — reverts a previous commit"
echo ""
echo -e "  ${BOLD}Allowed scopes (frontend):${RESET}"
echo -e "  ${DIM}auth, room, video-sync, domain, data, presentation, infra${RESET}"
echo ""
echo -e "  ${BOLD}BREAKING CHANGE:${RESET} add ${CYAN}BREAKING CHANGE: <description>${RESET} in the commit footer"
echo -e "  ${DIM}This triggers a MAJOR version bump regardless of the type.${RESET}"
echo ""
echo -e "  ${BOLD}Examples:${RESET}"
echo -e "  ${GREEN}feat(auth): implement RegisterUseCase with email uniqueness validation${RESET}"
echo -e "  ${GREEN}test(auth): write unit tests for LoginCubit initial state${RESET}"
echo -e "  ${GREEN}fix(room): correct ownership check on room deletion endpoint${RESET}"
echo -e "  ${GREEN}chore(infra): update Flutter SDK to 3.22.0${RESET}"
echo ""
echo -e "  ${BOLD}Received:${RESET}"
echo -e "  ${RED}${MSG}${RESET}"
echo ""

# Attempt to identify the specific error for a more targeted hint.
if ! echo "$MSG" | grep -qE "^(${ALLOWED_TYPES})"; then
  log_warn "Hint: the type '$(echo "$MSG" | cut -d'(' -f1 | cut -d':' -f1)' is not in the allowed list."
elif ! echo "$MSG" | grep -qE ": "; then
  log_warn "Hint: missing ': ' separator between the type/scope and the description."
elif echo "$MSG" | grep -qE "^[a-z]+\([A-Z]"; then
  log_warn "Hint: scope must be lowercase."
fi

echo ""
exit 1