import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/entities/user_entity.dart';

part 'user_model.freezed.dart';

/// Data layer model for the backend's authentication response body.
///
/// The backend's `AuthResponseDto` (register, login, refresh) returns a
/// flat JSON object with a nested user profile and top-level tokens:
/// ```json
/// {
///   "user": { "id": "...", "email": "...", "username": "...",
///             "role": "registered", "createdAt": "..." },
///   "accessToken": "...",
///   "refreshToken": "..."
/// }
/// ```
/// [UserModel] mirrors this shape directly rather than only the nested
/// `user` object, per the Interface Contracts' `IAuthRemoteDataSource`
/// signatures (`register`/`login` return `Future<UserModel>` — a single
/// type carrying both the profile and the session tokens, avoiding a
/// second round-trip or a separate wrapper type).
///
/// `fromJson` is written by hand rather than generated by
/// `json_serializable`: the nested `user` object does not map onto this
/// model's flat field list, so the default generated codec would not
/// apply here. `toJson` is intentionally not provided — this model is
/// only ever deserialised from a server response, never serialised back
/// out.
///
/// [toDomain] is the sole crossing point between this data-layer shape
/// and the domain's [UserEntity] — it also has the side effect of
/// silently dropping the token fields, which the domain entity has no
/// business carrying (the repository is responsible for persisting them
/// via `IAuthLocalDataSource` before ever calling `toDomain()`).
@freezed
sealed class UserModel with _$UserModel {
  const UserModel._();

  const factory UserModel({
    required String id,
    required String email,
    required String username,
    required String role,
    required DateTime createdAt,
    required String accessToken,
    required String refreshToken,
  }) = _UserModel;

  /// Parses the backend's `AuthResponseDto` JSON body.
  ///
  /// Exact wiring of this factory against a live Dio response (including
  /// malformed-payload handling) is exercised by
  /// `AuthRemoteDataSourceImpl.register()` and its tests; this
  /// factory itself makes no assumption about the transport, only about
  /// the JSON shape.
  factory UserModel.fromJson(Map<String, dynamic> json) {
    final user = json['user'] as Map<String, dynamic>;
    return UserModel(
      id: user['id'] as String,
      email: user['email'] as String,
      username: user['username'] as String,
      role: user['role'] as String,
      createdAt: DateTime.parse(user['createdAt'] as String),
      accessToken: json['accessToken'] as String,
      refreshToken: json['refreshToken'] as String,
    );
  }

  /// Converts this data-layer model to the domain's [UserEntity].
  ///
  /// Maps the backend's `username` wire field to [UserEntity.displayName]
  /// (see `UserEntity` class-level doc for the naming rationale) and
  /// parses the string `role` into the [UserRole] enum. Token fields are
  /// intentionally not carried over — see class-level doc.
  UserEntity toDomain() {
    return UserEntity(
      id: id,
      email: email,
      displayName: username,
      role: UserRole.values.byName(role),
      createdAt: createdAt,
    );
  }
}
